/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICommunicator, ICommunicatorInterface } from "../ICommunicator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "string",
        name: "messageContent",
        type: "string",
      },
      {
        internalType: "uint64",
        name: "destinationChainSelector",
        type: "uint64",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICommunicator__factory {
  static readonly abi = _abi;
  static createInterface(): ICommunicatorInterface {
    return new utils.Interface(_abi) as ICommunicatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICommunicator {
    return new Contract(address, _abi, signerOrProvider) as ICommunicator;
  }
}
