/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace FunctionsResponse {
  export type CommitmentStruct = {
    requestId: BytesLike;
    coordinator: string;
    estimatedTotalCostJuels: BigNumberish;
    client: string;
    subscriptionId: BigNumberish;
    callbackGasLimit: BigNumberish;
    adminFee: BigNumberish;
    donFee: BigNumberish;
    gasOverheadBeforeCallback: BigNumberish;
    gasOverheadAfterCallback: BigNumberish;
    timeoutTimestamp: BigNumberish;
  };

  export type CommitmentStructOutput = [
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    number,
    number,
    number
  ] & {
    requestId: string;
    coordinator: string;
    estimatedTotalCostJuels: BigNumber;
    client: string;
    subscriptionId: BigNumber;
    callbackGasLimit: number;
    adminFee: BigNumber;
    donFee: BigNumber;
    gasOverheadBeforeCallback: number;
    gasOverheadAfterCallback: number;
    timeoutTimestamp: number;
  };
}

export interface IFunctionsRouterInterface extends utils.Interface {
  contractName: "IFunctionsRouter";
  functions: {
    "fulfill(bytes,bytes,uint96,uint96,address,(bytes32,address,uint96,address,uint64,uint32,uint72,uint72,uint40,uint40,uint32))": FunctionFragment;
    "getAdminFee()": FunctionFragment;
    "getAllowListId()": FunctionFragment;
    "getContractById(bytes32)": FunctionFragment;
    "getProposedContractById(bytes32)": FunctionFragment;
    "getProposedContractSet()": FunctionFragment;
    "isValidCallbackGasLimit(uint64,uint32)": FunctionFragment;
    "pause()": FunctionFragment;
    "proposeContractsUpdate(bytes32[],address[])": FunctionFragment;
    "sendRequest(uint64,bytes,uint16,uint32,bytes32)": FunctionFragment;
    "sendRequestToProposed(uint64,bytes,uint16,uint32,bytes32)": FunctionFragment;
    "setAllowListId(bytes32)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateContracts()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fulfill",
    values: [
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string,
      FunctionsResponse.CommitmentStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowListId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposedContractById",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposedContractSet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isValidCallbackGasLimit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeContractsUpdate",
    values: [BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "sendRequest",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendRequestToProposed",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowListId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateContracts",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "fulfill", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdminFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowListId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposedContractById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposedContractSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidCallbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeContractsUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendRequestToProposed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowListId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateContracts",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFunctionsRouter extends BaseContract {
  contractName: "IFunctionsRouter";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFunctionsRouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fulfill(
      response: BytesLike,
      err: BytesLike,
      juelsPerGas: BigNumberish,
      costWithoutFulfillment: BigNumberish,
      transmitter: string,
      commitment: FunctionsResponse.CommitmentStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAdminFee(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { adminFee: BigNumber }>;

    getAllowListId(overrides?: CallOverrides): Promise<[string]>;

    getContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getProposedContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getProposedContractSet(
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;

    isValidCallbackGasLimit(
      subscriptionId: BigNumberish,
      callbackGasLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proposeContractsUpdate(
      proposalSetIds: BytesLike[],
      proposalSetAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendRequest(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendRequestToProposed(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAllowListId(
      allowListId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateContracts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  fulfill(
    response: BytesLike,
    err: BytesLike,
    juelsPerGas: BigNumberish,
    costWithoutFulfillment: BigNumberish,
    transmitter: string,
    commitment: FunctionsResponse.CommitmentStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAdminFee(overrides?: CallOverrides): Promise<BigNumber>;

  getAllowListId(overrides?: CallOverrides): Promise<string>;

  getContractById(id: BytesLike, overrides?: CallOverrides): Promise<string>;

  getProposedContractById(
    id: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getProposedContractSet(
    overrides?: CallOverrides
  ): Promise<[string[], string[]]>;

  isValidCallbackGasLimit(
    subscriptionId: BigNumberish,
    callbackGasLimit: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proposeContractsUpdate(
    proposalSetIds: BytesLike[],
    proposalSetAddresses: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendRequest(
    subscriptionId: BigNumberish,
    data: BytesLike,
    dataVersion: BigNumberish,
    callbackGasLimit: BigNumberish,
    donId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendRequestToProposed(
    subscriptionId: BigNumberish,
    data: BytesLike,
    dataVersion: BigNumberish,
    callbackGasLimit: BigNumberish,
    donId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAllowListId(
    allowListId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateContracts(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fulfill(
      response: BytesLike,
      err: BytesLike,
      juelsPerGas: BigNumberish,
      costWithoutFulfillment: BigNumberish,
      transmitter: string,
      commitment: FunctionsResponse.CommitmentStruct,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber]>;

    getAdminFee(overrides?: CallOverrides): Promise<BigNumber>;

    getAllowListId(overrides?: CallOverrides): Promise<string>;

    getContractById(id: BytesLike, overrides?: CallOverrides): Promise<string>;

    getProposedContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getProposedContractSet(
      overrides?: CallOverrides
    ): Promise<[string[], string[]]>;

    isValidCallbackGasLimit(
      subscriptionId: BigNumberish,
      callbackGasLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pause(overrides?: CallOverrides): Promise<void>;

    proposeContractsUpdate(
      proposalSetIds: BytesLike[],
      proposalSetAddresses: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    sendRequest(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    sendRequestToProposed(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setAllowListId(
      allowListId: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateContracts(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    fulfill(
      response: BytesLike,
      err: BytesLike,
      juelsPerGas: BigNumberish,
      costWithoutFulfillment: BigNumberish,
      transmitter: string,
      commitment: FunctionsResponse.CommitmentStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAdminFee(overrides?: CallOverrides): Promise<BigNumber>;

    getAllowListId(overrides?: CallOverrides): Promise<BigNumber>;

    getContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposedContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposedContractSet(overrides?: CallOverrides): Promise<BigNumber>;

    isValidCallbackGasLimit(
      subscriptionId: BigNumberish,
      callbackGasLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proposeContractsUpdate(
      proposalSetIds: BytesLike[],
      proposalSetAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendRequest(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendRequestToProposed(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAllowListId(
      allowListId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateContracts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fulfill(
      response: BytesLike,
      err: BytesLike,
      juelsPerGas: BigNumberish,
      costWithoutFulfillment: BigNumberish,
      transmitter: string,
      commitment: FunctionsResponse.CommitmentStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAdminFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllowListId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposedContractById(
      id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposedContractSet(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidCallbackGasLimit(
      subscriptionId: BigNumberish,
      callbackGasLimit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proposeContractsUpdate(
      proposalSetIds: BytesLike[],
      proposalSetAddresses: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendRequest(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendRequestToProposed(
      subscriptionId: BigNumberish,
      data: BytesLike,
      dataVersion: BigNumberish,
      callbackGasLimit: BigNumberish,
      donId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAllowListId(
      allowListId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateContracts(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
