/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IFunctionsSubscriptions {
  export type ConsumerStruct = {
    allowed: boolean;
    initiatedRequests: BigNumberish;
    completedRequests: BigNumberish;
  };

  export type ConsumerStructOutput = [boolean, BigNumber, BigNumber] & {
    allowed: boolean;
    initiatedRequests: BigNumber;
    completedRequests: BigNumber;
  };

  export type SubscriptionStruct = {
    balance: BigNumberish;
    owner: string;
    blockedBalance: BigNumberish;
    proposedOwner: string;
    consumers: string[];
    flags: BytesLike;
  };

  export type SubscriptionStructOutput = [
    BigNumber,
    string,
    BigNumber,
    string,
    string[],
    string
  ] & {
    balance: BigNumber;
    owner: string;
    blockedBalance: BigNumber;
    proposedOwner: string;
    consumers: string[];
    flags: string;
  };
}

export declare namespace FunctionsResponse {
  export type CommitmentStruct = {
    requestId: BytesLike;
    coordinator: string;
    estimatedTotalCostJuels: BigNumberish;
    client: string;
    subscriptionId: BigNumberish;
    callbackGasLimit: BigNumberish;
    adminFee: BigNumberish;
    donFee: BigNumberish;
    gasOverheadBeforeCallback: BigNumberish;
    gasOverheadAfterCallback: BigNumberish;
    timeoutTimestamp: BigNumberish;
  };

  export type CommitmentStructOutput = [
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    number,
    BigNumber,
    BigNumber,
    number,
    number,
    number
  ] & {
    requestId: string;
    coordinator: string;
    estimatedTotalCostJuels: BigNumber;
    client: string;
    subscriptionId: BigNumber;
    callbackGasLimit: number;
    adminFee: BigNumber;
    donFee: BigNumber;
    gasOverheadBeforeCallback: number;
    gasOverheadAfterCallback: number;
    timeoutTimestamp: number;
  };
}

export interface IFunctionsSubscriptionsInterface extends utils.Interface {
  contractName: "IFunctionsSubscriptions";
  functions: {
    "acceptSubscriptionOwnerTransfer(uint64)": FunctionFragment;
    "addConsumer(uint64,address)": FunctionFragment;
    "cancelSubscription(uint64,address)": FunctionFragment;
    "createSubscription()": FunctionFragment;
    "createSubscriptionWithConsumer(address)": FunctionFragment;
    "getConsumer(address,uint64)": FunctionFragment;
    "getFlags(uint64)": FunctionFragment;
    "getSubscription(uint64)": FunctionFragment;
    "getSubscriptionCount()": FunctionFragment;
    "getSubscriptionsInRange(uint64,uint64)": FunctionFragment;
    "getTotalBalance()": FunctionFragment;
    "oracleWithdraw(address,uint96)": FunctionFragment;
    "ownerCancelSubscription(uint64)": FunctionFragment;
    "pendingRequestExists(uint64)": FunctionFragment;
    "proposeSubscriptionOwnerTransfer(uint64,address)": FunctionFragment;
    "recoverFunds(address)": FunctionFragment;
    "removeConsumer(uint64,address)": FunctionFragment;
    "setFlags(uint64,bytes32)": FunctionFragment;
    "timeoutRequests((bytes32,address,uint96,address,uint64,uint32,uint72,uint72,uint40,uint40,uint32)[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addConsumer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscriptionWithConsumer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getConsumer",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFlags",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptionsInRange",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleWithdraw",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerCancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeSubscriptionOwnerTransfer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFunds",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeConsumer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFlags",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timeoutRequests",
    values: [FunctionsResponse.CommitmentStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscriptionWithConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFlags", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptionsInRange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerCancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFlags", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeoutRequests",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFunctionsSubscriptions extends BaseContract {
  contractName: "IFunctionsSubscriptions";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFunctionsSubscriptionsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelSubscription(
      subscriptionId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSubscription(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createSubscriptionWithConsumer(
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getConsumer(
      client: string,
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IFunctionsSubscriptions.ConsumerStructOutput]>;

    getFlags(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSubscription(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IFunctionsSubscriptions.SubscriptionStructOutput]>;

    getSubscriptionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSubscriptionsInRange(
      subscriptionIdStart: BigNumberish,
      subscriptionIdEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[IFunctionsSubscriptions.SubscriptionStructOutput[]]>;

    getTotalBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    oracleWithdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ownerCancelSubscription(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pendingRequestExists(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    proposeSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    recoverFunds(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFlags(
      subscriptionId: BigNumberish,
      flags: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    timeoutRequests(
      requestsToTimeoutByCommitment: FunctionsResponse.CommitmentStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptSubscriptionOwnerTransfer(
    subscriptionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addConsumer(
    subscriptionId: BigNumberish,
    consumer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelSubscription(
    subscriptionId: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSubscription(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createSubscriptionWithConsumer(
    consumer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getConsumer(
    client: string,
    subscriptionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IFunctionsSubscriptions.ConsumerStructOutput>;

  getFlags(
    subscriptionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getSubscription(
    subscriptionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IFunctionsSubscriptions.SubscriptionStructOutput>;

  getSubscriptionCount(overrides?: CallOverrides): Promise<BigNumber>;

  getSubscriptionsInRange(
    subscriptionIdStart: BigNumberish,
    subscriptionIdEnd: BigNumberish,
    overrides?: CallOverrides
  ): Promise<IFunctionsSubscriptions.SubscriptionStructOutput[]>;

  getTotalBalance(overrides?: CallOverrides): Promise<BigNumber>;

  oracleWithdraw(
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ownerCancelSubscription(
    subscriptionId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pendingRequestExists(
    subscriptionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  proposeSubscriptionOwnerTransfer(
    subscriptionId: BigNumberish,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  recoverFunds(
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeConsumer(
    subscriptionId: BigNumberish,
    consumer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFlags(
    subscriptionId: BigNumberish,
    flags: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  timeoutRequests(
    requestsToTimeoutByCommitment: FunctionsResponse.CommitmentStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelSubscription(
      subscriptionId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    createSubscription(overrides?: CallOverrides): Promise<BigNumber>;

    createSubscriptionWithConsumer(
      consumer: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConsumer(
      client: string,
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IFunctionsSubscriptions.ConsumerStructOutput>;

    getFlags(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getSubscription(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IFunctionsSubscriptions.SubscriptionStructOutput>;

    getSubscriptionCount(overrides?: CallOverrides): Promise<BigNumber>;

    getSubscriptionsInRange(
      subscriptionIdStart: BigNumberish,
      subscriptionIdEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<IFunctionsSubscriptions.SubscriptionStructOutput[]>;

    getTotalBalance(overrides?: CallOverrides): Promise<BigNumber>;

    oracleWithdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerCancelSubscription(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pendingRequestExists(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proposeSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    recoverFunds(to: string, overrides?: CallOverrides): Promise<void>;

    removeConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFlags(
      subscriptionId: BigNumberish,
      flags: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    timeoutRequests(
      requestsToTimeoutByCommitment: FunctionsResponse.CommitmentStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    acceptSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelSubscription(
      subscriptionId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSubscription(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createSubscriptionWithConsumer(
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getConsumer(
      client: string,
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFlags(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSubscription(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSubscriptionCount(overrides?: CallOverrides): Promise<BigNumber>;

    getSubscriptionsInRange(
      subscriptionIdStart: BigNumberish,
      subscriptionIdEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalBalance(overrides?: CallOverrides): Promise<BigNumber>;

    oracleWithdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ownerCancelSubscription(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pendingRequestExists(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposeSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    recoverFunds(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFlags(
      subscriptionId: BigNumberish,
      flags: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    timeoutRequests(
      requestsToTimeoutByCommitment: FunctionsResponse.CommitmentStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelSubscription(
      subscriptionId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSubscription(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createSubscriptionWithConsumer(
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getConsumer(
      client: string,
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFlags(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscription(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscriptionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSubscriptionsInRange(
      subscriptionIdStart: BigNumberish,
      subscriptionIdEnd: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    oracleWithdraw(
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ownerCancelSubscription(
      subscriptionId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pendingRequestExists(
      subscriptionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposeSubscriptionOwnerTransfer(
      subscriptionId: BigNumberish,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    recoverFunds(
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeConsumer(
      subscriptionId: BigNumberish,
      consumer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFlags(
      subscriptionId: BigNumberish,
      flags: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    timeoutRequests(
      requestsToTimeoutByCommitment: FunctionsResponse.CommitmentStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
