import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import { useAccount } from "wagmi";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { isConnected } = useAccount()
  const router = useRouter()

  useEffect(() => {
    if(isConnected) {
      router.push('/dashboard')
    }
  }, [isConnected, router])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cross Carbon</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Hero />
      <footer className={styles.footer}>
        <a >
          Made with ❤️ 🇨🇴 🇨🇿
        </a>
      </footer>
    </div>
  );
};

export default Home;
